## 1. Importing Libraries

In [4]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix

## 2. Importing Dataset and Preprocessing

In [5]:
df = pd.read_csv("../data/raw_station_data.csv")

In [6]:
df.isnull().sum()

Station_ID              0
Daily_Usage             0
Downtime_Hours          0
Maintenance_Cost        0
Requires_Maintenance    0
dtype: int64

In [7]:
duplicates = df.duplicated()
print("Total Number of Duplicates present in dataset :",duplicates.sum())

Total Number of Duplicates present in dataset : 0


In [8]:
y = df["Requires_Maintenance"]
X = df.drop("Requires_Maintenance",axis=1)

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

## 3. Logistic Regression

In [10]:
model_LR = LogisticRegression()
model_LR.fit(X_train_scaled,y_train)
y_pred1 = model_LR.predict(X_test_scaled)
y_pred1

array([0, 0, 1, 1])

In [11]:
print("Classification Report for Logistic Regression : \n",classification_report(y_test,y_pred1))

Classification Report for Logistic Regression : 
               precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4



In [12]:
print("Confusion Matrix for Logistic Regression :\n",confusion_matrix(y_test,y_pred1))

Confusion Matrix for Logistic Regression :
 [[2 1]
 [0 1]]


## 4. Random Forest Classifier

In [13]:
model_RF = RandomForestClassifier(random_state=42)
model_RF.fit(X_train, y_train)
y_pred2 = model_RF.predict(X_test)
y_pred2

array([0, 0, 1, 1])

In [14]:
print("Classification Report for Random Forest Classifier : \n",classification_report(y_test,y_pred2))

Classification Report for Random Forest Classifier : 
               precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4



In [15]:
print("Confusion Matrix for Random Forest Classifier:\n",confusion_matrix(y_test,y_pred2))

Confusion Matrix for Random Forest Classifier:
 [[2 1]
 [0 1]]
